services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  scaler-service:
    build: ./saas-cloud-scaler
    ports:
      - "3003:3003"
    depends_on:
      - prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3004:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  postgres:
    image: postgres:15
    container_name: saas_user_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  user-service:
    build: ./saas-cloud-scaler-user
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-network

  auth-service:
    build: ./saas-cloud-scaler-auth
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    networks:
      - app-network

  gateway-service:
    build: ./saas-cloud-scaler-gateway
    ports:
      - "3002:3002"
    depends_on:
      - auth-service
      - user-service

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-data:
